# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47774be3a0ff2a3607abb2e6f9d51fa17e948a1c7546954360abbc2c258318d6309078cc18beb66b0adcbbb92302f949e5224735c453e391cb59cae8785375de

test:
  secret_key_base: fbac564ba41d4af2ff402f3a63c2990178a73553cd89cccf1b501c4eb89a037f30599251a51846e3ad6a402638db08b8dbc80061e022626b2cc486770c9e3750

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
